---
pagetitle: "Tealium: Course Template"
subtitle: ""
toc: false
date: ""
sidebar: false
format:
  html:
    css: "assets/css/home.css"
    number-sections: false
    title-block-banner: false
    page-layout: full
    anchor-sections: false
execute:
  freeze: false
hero-gallery:
  images: assets/images/hero/
resources:
  - assets/images/binary.svg
filters:
  - assets/hero-gallery.lua
---

::: {.home-container}
::: {.home-inner}

## [Tealium: Course Template]{.large}
### A quarto course template

- [Report](reports/sample/index.html)
- [Presentation](slides/sample/index.html)

For usage instructions and demo examples, see [Contents](home_contents.html)

---

::: small
Updated: {{< meta current_date >}}  at {{< meta current_time >}} .
:::

:::
:::

::: {#particles-js}

:::

<script src="http://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
<script>
  particlesJS("particles-js", {
  particles: {
    number: { value: 80, density: { enable: true, value_area: 800 } },
    color: { value: "#a6cbcf" },
    shape: {
      type: "circle",
      stroke: { width: 0, color: "#000000" },
      polygon: { nb_sides: 5 },
      image: { src: "img/github.svg", width: 100, height: 100 }
    },
    opacity: {
      value: 1,
      random: false,
      anim: { enable: false, speed: 1, opacity_min: 0.1, sync: false }
    },
    size: {
      value: 5,
      random: true,
      anim: { enable: false, speed: 40, size_min: 0.1, sync: false }
    },
    line_linked: {
      enable: true,
      distance: 150,
      color: "#a6cbcf",
      opacity: 0.4,
      width: 1
    },
    move: {
      enable: true,
      speed: 1,
      direction: "none",
      random: false,
      straight: false,
      out_mode: "out",
      bounce: false,
      attract: { enable: false, rotateX: 600, rotateY: 1200 }
    }
  },
  interactivity: {
    detect_on: "canvas",
    events: {
      onhover: { enable: true, mode: "repulse" },
      onclick: { enable: true, mode: "push" },
      resize: true
    },
    modes: {
      grab: { distance: 400, line_linked: { opacity: 1 } },
      bubble: { distance: 400, size: 40, duration: 2, opacity: 8, speed: 3 },
      repulse: { distance: 50, duration: 0.4 },
      push: { particles_nb: 4 },
      remove: { particles_nb: 2 }
    }
  },
  retina_detect: true
});
</script>
